sql = "CREATE TABLE ProductData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(30) NOT NULL,
    productName VARCHAR(30) NOT NULL,
    price VARCHAR(30) NOT NULL,
    productType VARCHAR(30) NOT NULL,
    parametrs VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )";